services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/Omar_52_21184
    ports:
      - "21184:8080"
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Omar_52_21184
    ports:
      - "5432:5432"
